apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-arch-container-dotnet
  labels:
    app: multi-arch-container-dotnet
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: multi-arch-container-dotnet
  template:
    metadata:
      labels:
        app: multi-arch-container-dotnet
    spec:
      containers:
      - name: primary
        image: ghcr.io/f2calv/multi-arch-container-dotnet:dev
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        # livenessProbe
        # readinessProbe
        # startupProbe
        env:
        - name: "ASPNETCORE_LOG"
          value: "Debug"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi