apiVersion: v1
kind: Service
metadata:
  name: multi-arch-container-dotnet-svc
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: multi-arch-container-dotnet