apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multi-arch-container-dotnet.fullname" . }}
  labels:
    {{- include "multi-arch-container-dotnet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "multi-arch-container-dotnet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multi-arch-container-dotnet.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "multi-arch-container-dotnet.serviceAccountName" . }}
      {{- if hasKey .Values "podSecurityContext" }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if hasKey .Values "securityContext" }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if hasKey .Values "git" }}
            - name: "GIT_REPOSITORY"
              value: {{ .Values.git.repository | default "" | quote }}
            - name: "GIT_BRANCH"
              value: {{ .Values.git.branch | default "" | quote }}
            - name: "GIT_COMMIT"
              value: {{ .Values.git.commit | default "" | quote }}
            {{- end }}
            - name: "GIT_TAG"
              value: {{ .Values.image.tag | default .Chart.AppVersion }}
            {{- if hasKey .Values "github" }}
            - name: "GITHUB_WORKFLOW"
              value: {{ .Values.github.workflow | default "" | quote }}
            - name: "GITHUB_RUN_ID"
              value: {{ .Values.github.run_id | int64 | default 0 | quote }}
            - name: "GITHUB_RUN_NUMBER"
              value: {{ .Values.github.run_number | int64 | default 0 | quote }}
            {{- end }}
          {{- if hasKey .Values "livenessProbe" }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if hasKey .Values "readinessProbe" }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if hasKey .Values "resources" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
