{{- if and (hasKey .Values "service") (.Values.service) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multi-arch-container-dotnet.fullname" . }}
  labels:
    {{- include "multi-arch-container-dotnet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "multi-arch-container-dotnet.selectorLabels" . | nindent 4 }}
{{- end }}
