global using CasCap.Models;
global using CasCap.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System.ComponentModel.DataAnnotations;
global using System.Runtime.InteropServices;
