name: build-chart

on:
  workflow_call:
    inputs:
      semVer:
        type: string
        description: e.g. 1.2.3-feature-my-feature.12
        required: true

jobs:
  build-chart:
    runs-on: ubuntu-latest
    permissions:
      packages: write #for pushing helm package
    env:
      REGISTRY: ghcr.io
      #CHART_REPOSITORY: Note: set dynamically, i.e. github.repository_owner/charts/IMAGE_NAME
      GIT_TAG: ${{ inputs.semVer }}
    steps:
      - uses: actions/checkout@v3

      - name: set vars (1 of 3)
        run: |
          IMAGE_NAME=$(echo $REPOSITORY | sed "s|$USERNAME\/||g")
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: set vars (2 of 3)
        run: echo "CHART_REPOSITORY=${{ github.repository_owner }}/charts/$IMAGE_NAME" >> $GITHUB_ENV

      - name: set vars (3 of 3) #pulls helm version from devcontainer
        run: |
          apt-get install -y node-json5
          json5 -c .devcontainer/devcontainer.json
          HELM_VERSION_TO_INSTALL=$(cat .devcontainer/devcontainer.json | jq -r '.features[] | select(.helm | . != null).helm')
          echo "HELM_VERSION_TO_INSTALL=$HELM_VERSION_TO_INSTALL" >> $GITHUB_ENV
          echo $HELM_VERSION_TO_INSTALL

      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: helm registry login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${REGISTRY}/${CHART_REPOSITORY} --username ${{ github.repository_owner }} --password-stdin

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
        if: false #not implemented/working yet

      - name: chart-testing (setup)
        uses: helm/chart-testing-action@v2
        if: false #not implemented/working yet

      - name: chart-testing (run list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
        if: false #not implemented/working yet

      - name: chart-testing (run lint)
        run: ct lint
        if: false #not implemented/working yet

      - name: create kind cluster
        uses: helm/kind-action@v1
        #if: steps.list-changed.outputs.changed == 'true'
        if: false #not implemented/working yet

      - name: chart-testing (run install)
        run: ct install
        if: false #not implemented/working yet

      - name: helm package
        run: |
          helm package ${{ github.workspace }}/charts/$IMAGE_NAME/ --destination ${{ github.workspace }}/artifacts/ --app-version ${{ env.GIT_TAG }}
        if: false #not implemented/working yet

      - name: helm push
        run: |
          helm push ${{ github.workspace }}/artifacts/$IMAGE_NAME-0.1.0.tgz oci://ghcr.io/${{ github.repository_owner }}
        if: false #not implemented/working yet, need to change the chart version in filename
