name: versioning

on:
  workflow_call:
    outputs:
      semVer:
        description: i.e. 1.2.3
        value: ${{ jobs.get-version.outputs.semVer }}
      fullSemVer:
        description: i.e. 1.2.3-feature-my-feature.12
        value: ${{ jobs.get-version.outputs.fullSemVer }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: .NET 7.x SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: gitversion (1 of 3)
        run: |
          FILE=GitVersion.yml
          if [[ -f "$FILE" ]]; then
            echo "$FILE exists"
          else
            echo "::error file=GitVersion.yml::Repository versioning is managed by GitVersion, '$FILE' is therefore required!"
          fi

      - name: gitversion (2 of 3)
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x

      - name: gitversion (3 of 3)
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          additionalArguments: /nofetch