name: ci

on:
  workflow_call:

jobs:
  build_app:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: .NET 7.x SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: gitversion (1 of 2)
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x

      - name: gitversion (2 of 2)
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          additionalArguments: /nofetch